---
- name: Task to template lvmscluster 
  ansible.builtin.template:
    src: templates/lvms/lvm-cluster.yml.j2
    dest: '{{ playbook_dir }}/manifest/operators/lvms-operator/lvmscluster.yml'
    owner: '{{ local_user }}'
    group: '{{ local_group }}'
    mode: '0664'

## TODO ##
# test the following task

# - name: Task to delete image-registry-storage pvc
#   kubernetes.core.k8s:
#     kubeconfig: '/home/{{ local_user }}/.kube/config'
#     state: absent
#     name: image-registry-storage
#     namespace: openshift-image-registry
#     kind: PersistentVolumeClaim
#     apiVersion: v1

# - name: Task to create image-registry-storage pvc
#   kubernetes.core.k8s:
#     kubeconfig: '/home/{{ local_user }}/.kube/config'
#     state: present
#     name: image-registry-storage
#     namespace: openshift-image-registry
#     kind: PersistentVolumeClaim
#     apiVersion: v1
#     spec:
#       accessModes:
#         - ReadWriteOnce
#       resources:
#         requests:
#           storage: 100Gi
#       storageClassName: lvms-vg1
#       volumeMode: Filesystem

