---
- name: Ansible Playbook to automate deploying a sno cluster on your proxmox environment
  hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter your sudo password here"
      private: true
    - name: api_password
      prompt: "Enter the root password for your proxmox environment here"
      private: true
  become: true
  tasks:
    - name: Include preflight-check role
      ansible.builtin.include_role:
        name: preflight-checks
      
    - name: Include install-cluster role
      ansible.builtin.include_role:
        name: install-cluster

    - name: Include day2ops role
      ansible.builtin.include_role:
        name: day2ops

