---
- name: Ansible Playbook to automate deploying a sno cluster on your local machine
  hosts: localhost
  vars_files:
    - vars.yml
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter your sudo password here"
      private: true
    - name: api_password
      prompt: "Enter your proxmox api password here"
      private: false
  become: true
  tasks:
    - name: Include preflight-check role
      ansible.builtin.include_role:
        name: preflight-checks