- name: Include authentication tasks
  ansible.builtin.include_tasks: '{{ playbook_dir }}/preflight-checks/tasks/authenticate.yml'

- name: Task Query API for {{ cluster_credential_type }} file 
  ansible.builtin.uri:
    url: 'https://api.openshift.com/api/assisted-install/v2/clusters/{{ cluster_id }}/downloads/credentials?file_name={{ cluster_credential_type }}'
    method: GET
    body_format: json
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    body:
      cluster_id: '{{ cluster_id }}'
      file_name: '{{ cluster_credential_type }}'
    status_code: 200
    return_content: true
  register: cluster_credentials_result

- name: Task to copy content to ~/.kube/config
  ansible.builtin.copy:
    content: '{{ cluster_credentials_result.content }}'
    dest: '/home/{{ local_user }}/.kube/config'
    owner: '{{ local_user }}'
    group: '{{ local_group }}'
    mode: '0664'

- debug:
    msg: '{{ cluster_credentials_result }}'