---
# tasks file for day2ops
- name: Include cluster tasks
  ansible.builtin.include_tasks: cluster.yml

- name: Include kubeconfig tasks
  ansible.builtin.include_tasks: kubeconfig.yml

- name: Include vm-disk tasks
  ansible.builtin.include_tasks: vm-disk.yml

# - name: Include install-operator tasks
#   ansible.builtin.include_tasks: install-operator.yml
#   loop: '{{ operators }}'





  
  


    