---
- name: Task to extract the offline token from {{ assisted_installer_credentials.token_path }}
  ansible.builtin.set_fact:
    offline_token: '{{ lookup("file", assisted_installer_credentials.token_path) }}'

- name: Task to login provided offline_token
  ansible.builtin.command:
    cmd: 'ocm login --token={{ offline_token }}'

- name: Task to generate a new API token for assisted installer
  ansible.builtin.command:
    cmd: 'ocm token'
  register: api_token_results

- name: Task to update the api_token fact with results from previous task 
  ansible.builtin.set_fact: 
    api_token: '{{ api_token_results.stdout }}'