---
- name: Task Query API for all existing clusters
  ansible.builtin.uri:
    url: https://api.openshift.com/api/assisted-install/v2/clusters
    method: GET
    body_format: json
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    status_code: 200
    return_content: true
  register: cluster_results

- debug:
    msg: "{{ cluster_results }}"

- name: Task to reauthenticate
  ansible.builtin.include_tasks: "{{ playbook_dir }}/preflight-checks/tasks/authenticate.yml"

- name: Task to register cluster using API
  ansible.builtin.uri:
    url: https://api.openshift.com/api/assisted-install/v2/clusters
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    status_code: 201
    body:
      name: '{{ vmname }}'
      high_availability_mode: "{{ registerCluster.high_availability_mode }}"
      openshift_version: "{{ registerCluster.openshift_version }}"
      pull_secret: "{{ pull_secret | to_json }}"
      base_dns_domain: "{{ base_dns_domain }}"
  register: cluster_register_result

- name: init cluster id variable
  ansible.builtin.set_fact:
    cluster_id: "{{ cluster_register_result.json.id }}"

- name: POST request to create an infra environment
  ansible.builtin.uri:
    url: "https://api.openshift.com/api/assisted-install/v2/infra-envs"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    body:
      name: "{{ infraEnvironment.name }}"
      image_type: "{{ infraEnvironment.image_type }}"
      cpu_architecture: "{{ infraEnvironment.cpu_architecture }}"
      cluster_id: "{{ cluster_id }}"
      pull_secret: "{{ pull_secret | to_json }}"
    return_content: yes
    status_code: 201
  register: infra_env_result

- name: Task to set download_url variable to the download_url of the infra environment
  ansible.builtin.set_fact:
    download_url: "{{ infra_env_result.json.download_url }}"



