- name: task to wait before checking if the cluster is ready
  ansible.builtin.pause:
    minutes: "{{ minutes }}"

- name: task to reauthenticate
  ansible.builtin.include_tasks: "{{ playbook_dir }}/assisted_installer/tasks/authenticate.yml"

- name: hit api for a cluster with the id {{ cluster_id }} and wait until the cluster is ready to install or already installing or already installed
  ansible.builtin.uri:
    url: https://api.openshift.com/api/assisted-install/v2/clusters/{{ cluster_id }}/
    method: GET
    body_format: json
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    body:
      openshift_cluster_id: "{{ cluster_id }}"
    status_code: 200
    return_content: true
  register: cluster_results
  retries: 150
  delay: 5