- name: task to wait before checking if the cluster's host is available
  ansible.builtin.pause:
    minutes: "{{ minutes }}"

- name: task to reauthenticate
  ansible.builtin.include_tasks: "{{ playbook_dir }}/assisted_installer/tasks/authenticate.yml"

- name: hit api for a list of all hosts with the id {{ cluster_id }} and wait until the host is installed or pending user action
  ansible.builtin.uri:
    url: https://api.openshift.com/api/assisted-install/v2/clusters/{{ cluster_id }}/hosts/
    method: GET
    body_format: json
    headers:
      Authorization: "Bearer {{ api_token }}"
      Content-Type: "application/json"
    body:
      cluster_id: "{{ cluster_id }}"
    status_code: 200
    return_content: true
  register: host_results
  until: host_results.json[0].status == "installed"
  retries: 150
  delay: 5