---
- name: template the dns confiuration
  ansible.builtin.template:
    src: "templates/zoneFile.j2"
    dest: "/etc/bind/db.{{ base_dns_domain }}"
    owner: root
    group: root
    mode: 0644

- name: template the named.conf.local file
  ansible.builtin.template:
    src: "templates/named.conf.local.j2"
    dest: "/etc/bind/named.conf.local"
    owner: root
    group: root
    mode: 0644

- name: add line to resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 127.0.0.1"
    state: present
    insertbefore: BOF

- name: restart bind service
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Ping the domain
  command: "ping -c 4 api.{{ cluster_base_domain }}"
  register: ping_result
  ignore_errors: true

- name: Check if ping was successful
  assert:
    that:
      - "'64 bytes from' in ping_result.stdout"
      - ping_result.rc == 0
    fail_msg: "Ping failed for api.{{ cluster_base_domain }}"
    success_msg: "Ping successful for api.{{ cluster_base_domain }}"