---
# tasks file for install_cluster



# - name: include apiClusterReady tasks
#   ansible.builtin.include_tasks: apiClusterReady.yml

# - name: include apiInstallCluster tasks
#   ansible.builtin.include_tasks: apiInstallCluster.yml

# - name: include apiInstallHost tasks
#   ansible.builtin.include_tasks: apiInstallHost.yml

# - name: include apiFinalizeInstall tasks
#   ansible.builtin.include_tasks: apiFinalizeInstall.yml

