---
- name: task to format the pull secret from {{ pull_secret_path }}
  ansible.builtin.set_fact:
    raw_pull_secret: "{{ lookup('file', pull_secret_path) | from_json }}"

- debug:
    msg: "{{ raw_pull_secret }}"
  when: debug_mode == true