---
- name: Create bridge netdev configuration for br0
  copy:
    content: |
      [NetDev]
      Name={{ interfaces.bridge.name }}
      Kind=bridge
    dest: /etc/systemd/network/25-bridge-br0.netdev

- name: Configure br0 with IP details
  copy:
    content: |
      [Match]
      Name={{ interfaces.bridge.name }}

      [Network]
      DHCP=yes
      Gateway={{ interfaces.bridge.router }}
      DNS=192.168.1.83
      Domains=~.
    dest: /etc/systemd/network/20-br0.network

- name: Update enp7s0 configuration to be part of br0
  copy:
    content: |
      [Match]
      Name=enp7s0

      [Network]
      Bridge={{ interfaces.bridge.name }}
    dest: /etc/systemd/network/10-enp7s0.network

- name: Restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
