---
# tasks file for assisted_installer
- name: install packages on host
  ansible.builtin.apt:
    pkg: 
      - "{{ item }}"
  loop: "{{ packages }}"

- name: tasks to authenticate to api
  ansible.builtin.include_tasks: authenticate.yml

- name: validate cluster does not exist
  ansible.builtin.include_tasks: validateCluster.yml

- name: tasks to register cluster
  ansible.builtin.include_tasks: registerCluster.yml
  when: cluster_exists == false



