---
- name: Task to get the pull secret file status
  ansible.builtin.stat:
    path: '{{ assisted_installer_credentials["pull_secret_path"] }}'
  register: pull_secret_stat_results

- name: Task to get the token file status
  ansible.builtin.stat:
    path: '{{ assisted_installer_credentials["token_path"] }}'
  register: token_stat_results

- name: VALIDATION FAIL
  ansible.builtin.fail:
    msg: "It seems the token file is missing. Please check the path configured in the vars.yml file and try again."
  when: token_stat_results.stat.exists == false

- name: VALIDATION FAIL
  ansible.builtin.fail:
    msg: "It seems the pull-secret file is missing. Please check the path configured in the vars.yml file and try again."
  when: pull_secret_stat_results.stat.exists == false