---
- name: Task to ensure the iso path {{ isos.path }} exists
  ansible.builtin.file:
    path: '{{ isos.path }}'
    state: directory
    owner: '{{ local_user }}'
    group: '{{ local_group }}'
    mode: 0755

- name: Task to remove any existing iso images with the same name
  ansible.builtin.file:
    path: '{{ isos.path }}{{ isos.name }}'
    state: absent

- name: download url to iso path variable
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ isos.path }}{{ isos.name }}"
    owner: '{{ local_user }}'
    group: '{{ local_group }}'
    mode: 0755
