---
- name: get volume status
  ansible.builtin.stat:
    path: /var/lib/libvirt/images/{{ storagePool['default']['volume']['name'] }}
  register: volume_status

- name: define a new storage pool
  community.libvirt.virt_pool:
    command: define
    name: "{{ storagePool.default.name }}"
    xml: '{{ lookup("template", "templates/storagePool.xml.j2") }}'

- name: Build a storage pool if it does not exist
  community.libvirt.virt_pool:
    command: build
    name: "{{ storagePool.default.name }}"

- name: Start a storage pool
  community.libvirt.virt_pool:
    command: create
    name: "{{ storagePool.default.name }}"

- name: ensure volume with {{ storage }} GB exists
  ansible.builtin.command:
    cmd: "qemu-img create -f qcow2 {{ storagePool['default']['volume']['name'] }} {{ storage }}G"
    chdir: "{{ storagePool['default']['path'] }}"
  register: qemu_results
  when: volume_status.stat.exists == false

- debug:
    msg: "{{ qemu_results.stdout_lines }}"
  when: debug_mode == true and volume_status.stat.exists == false

- name: task to refresh the pool
  community.libvirt.virt_pool:
    name: default
    command: refresh